---
abstract: 'create JPEG previews without headers'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Image-JpegMinimal
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Imager: '0'
  MIME::Base64: '0'
  perl: '5.006'
resources:
  repository: http://github.com/Corion/image-jpegminimal
version: '0.01'
